[package]
name = "car-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
num-derive = "0.4.2"
num-traits = "0.2.19"
ts-rs = "9.0.1"

serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
time = "0.3.36"
